<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <Version>1.8.0</Version>
    <ApplicationIcon>Assets\server.ico</ApplicationIcon>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DaProdServer</AssemblyName>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\zone_map_names.txt" LogicalName="zone_map_names.txt" />
    <EmbeddedResource Include="Resources\zone_neighbors.txt" LogicalName="zone_neighbors.txt" />
    <EmbeddedResource Include="Resources\infusions.txt" LogicalName="infusions.txt" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
    <PackageReference Include="System.Management" Version="9.0.0" />
  </ItemGroup>
</Project>
