<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <Version>1.10.0</Version>
    <ApplicationIcon>Assets\launcher.ico</ApplicationIcon>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DaProdLauncher</AssemblyName>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\splash.png" LogicalName="splash.png" />
    <EmbeddedResource Include="..\..\addons\DaProdMod\toc.g" LogicalName="addon_toc.g" />
    <EmbeddedResource Include="..\..\addons\DaProdMod\main.lua" LogicalName="addon_main.lua" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="9.0.0" />
  </ItemGroup>
</Project>
